/* 
 * Employee API
 *
 * Sample API to perform Employee operations
 *
 * OpenAPI spec version: 1.0.0
 * Contact: arnoldchanliongco@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EmployeesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EmployeesApiTests
    {
        private EmployeesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EmployeesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmployeesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EmployeesApi
            //Assert.IsInstanceOfType(typeof(EmployeesApi), instance, "instance is a EmployeesApi");
        }

        /// <summary>
        /// Test ApiEmployeesGet
        /// </summary>
        [Test]
        public void ApiEmployeesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiEmployeesGet();
            //Assert.IsInstanceOf<List<Employee>> (response, "response is List<Employee>");
        }
        /// <summary>
        /// Test ApiEmployeesIdDelete
        /// </summary>
        [Test]
        public void ApiEmployeesIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiEmployeesIdDelete(id);
            
        }
        /// <summary>
        /// Test ApiEmployeesIdGet
        /// </summary>
        [Test]
        public void ApiEmployeesIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiEmployeesIdGet(id);
            //Assert.IsInstanceOf<Employee> (response, "response is Employee");
        }
        /// <summary>
        /// Test ApiEmployeesIdPut
        /// </summary>
        [Test]
        public void ApiEmployeesIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //Employee body = null;
            //instance.ApiEmployeesIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiEmployeesPost
        /// </summary>
        [Test]
        public void ApiEmployeesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Employee body = null;
            //var response = instance.ApiEmployeesPost(body);
            //Assert.IsInstanceOf<Employee> (response, "response is Employee");
        }
    }

}
