/* 
 * Employee API
 *
 * Sample API to perform Employee operations
 *
 * OpenAPI spec version: 1.0.0
 * Contact: arnoldchanliongco@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Employee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmployeeTests
    {
        // TODO uncomment below to declare an instance variable for Employee
        //private Employee instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Employee
            //instance = new Employee();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Employee
        /// </summary>
        [Test]
        public void EmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Employee
            //Assert.IsInstanceOfType<Employee> (instance, "variable 'instance' is a Employee");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'EmailId'
        /// </summary>
        [Test]
        public void EmailIdTest()
        {
            // TODO unit test for the property 'EmailId'
        }

    }

}
