/* 
 * Employee API
 *
 * Sample API to perform Employee operations
 *
 * OpenAPI spec version: 1.0.0
 * Contact: arnoldchanliongco@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProblemDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProblemDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ProblemDetails
        //private ProblemDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProblemDetails
            //instance = new ProblemDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProblemDetails
        /// </summary>
        [Test]
        public void ProblemDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProblemDetails
            //Assert.IsInstanceOfType<ProblemDetails> (instance, "variable 'instance' is a ProblemDetails");
        }



    }

}
